server:
  port: 8001
spring:
  application:
    name: UserProvider
  datasource:
    url: jdbc:mysql://localhost:3306/spring-test?serverTimezone=GMT%2B8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
ProviderVersion: UserProvider01-update:7.7.7V
